DROP TABLE BILLING_ENTRY CASCADE CONSTRAINTS
/
DROP TABLE BILLING_ENTRY_TYPE CASCADE CONSTRAINTS
/
DROP TABLE BILLINGS CASCADE CONSTRAINTS
/
DROP TABLE CLIENT_REGISTRATION CASCADE CONSTRAINTS
/
DROP TABLE COMPLAINTS CASCADE CONSTRAINTS
/
DROP TABLE CONTRACT_PRODUCT_ITEM CASCADE CONSTRAINTS
/
DROP TABLE CONTRACT_SERVICE_ITEM CASCADE CONSTRAINTS
/
DROP TABLE CONTRACT_STATUS CASCADE CONSTRAINTS
/
DROP TABLE CONTRACTS CASCADE CONSTRAINTS
/
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS
/
DROP TABLE EMPLOYEES CASCADE CONSTRAINTS
/
DROP TABLE MAIL_SETTINGS CASCADE CONSTRAINTS
/
DROP TABLE MAIL_SETTINGS_PROPERTIES CASCADE CONSTRAINTS
/
DROP TABLE PAYMENT_NOTIFICATION CASCADE CONSTRAINTS
/
DROP TABLE PAYMENTS CASCADE CONSTRAINTS
/
DROP TABLE PERSON CASCADE CONSTRAINTS
/
DROP TABLE PRODUCTS CASCADE CONSTRAINTS
/
DROP TABLE SERVICE_TYPES CASCADE CONSTRAINTS
/
DROP TABLE SERVICES CASCADE CONSTRAINTS
/
DROP TABLE USER_ROLE CASCADE CONSTRAINTS
/
DROP TABLE USERS CASCADE CONSTRAINTS
/
DROP SEQUENCE BILLING_ENTRY_TYPE_SEQ
/
DROP SEQUENCE BILLINGS_SEQ
/
DROP SEQUENCE COMPLAINTS_SEQ
/
DROP SEQUENCE CONTRACTS_SEQ
/
DROP SEQUENCE CTR_ITEM_SEQ
/
DROP SEQUENCE CTR_STATUS_SEQ
/
DROP SEQUENCE CUSTOMERS_SEQ
/
DROP SEQUENCE EMPLOYEE_SEQ
/
DROP SEQUENCE MAIL_SETTINGS_PROPERTIES_SEQ
/
DROP SEQUENCE MAIL_SETTINGS_SEQ
/
DROP SEQUENCE PAYMENT_NOTIFICATION_SEQ
/
DROP SEQUENCE PAYMENTS_SEQ
/
DROP SEQUENCE PERSON_SEQ
/
DROP SEQUENCE PRODUCTS_SEQ
/
DROP SEQUENCE SERVICE_TYPES_SEQ
/
DROP SEQUENCE SERVICES_SEQ
/
DROP SEQUENCE USER_SEQ
/
DROP SEQUENCE USR_ROLE_SEQ
/