INSERT INTO USER_ROLE(ROLE_TYPE, ROLE_DESC) VALUES ('ADMIN', 'ADMIN')
/
INSERT INTO USER_ROLE(ROLE_TYPE, ROLE_DESC) VALUES ('USER', 'USER')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Admin', 'Admin', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'ADMIN'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'admin'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Admin' AND LAST_NAME = 'Admin'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee1', 'Employee1', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp1', '86ea3363ba65c10f3f1ef299b126de29', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp1'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee1' AND LAST_NAME = 'Employee1'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee2', 'Employee2', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp2', '41ab3465e911f91509d3fae308f41f76', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp2'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee2' AND LAST_NAME = 'Employee2'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee3', 'Employee3', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp3', 'd4de43be683c4a47b9e5b52b2f191cb0', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp3'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee3' AND LAST_NAME = 'Employee3'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee4', 'Employee4', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp4', '4e2750e6d36e8e7ed970ee705ada5c8f', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp4'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee4' AND LAST_NAME = 'Employee4'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee5', 'Employee5', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp5', 'ec06b4fc95d91391e662149794b222d3', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp5'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee5' AND LAST_NAME = 'Employee5'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee6', 'Employee6', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp6', '09d57428ae91c05a90dd39a1bd87df34', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp6'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee6' AND LAST_NAME = 'Employee6'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee7', 'Employee7', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp7', '77780ab2f57504277c55ad44c1b32519', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp7'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee7' AND LAST_NAME = 'Employee7'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee8', 'Employee8', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp8', '261fc5eea5329f26e4a91081d4720c3c', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp8'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee8' AND LAST_NAME = 'Employee8'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee9', 'Employee9', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp9', '67382f06c432c4e691a3886e68ac42e9', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp9'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee9' AND LAST_NAME = 'Employee9'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee10', 'Employee10', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp10', '2441ff60ab68ee776070a1578d5da59d', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp10'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee10' AND LAST_NAME = 'Employee10'), 'testmail@somedomain.com', '00 000 00 00')
/