INSERT INTO CONTRACT_STATUS(STATUS, "DESC") VALUES('TEMPORARY', 'TEMPORARY')
/
INSERT INTO CONTRACT_STATUS(STATUS, "DESC") VALUES('ACCEPTED', 'ACCEPTED')
/
INSERT INTO CONTRACT_STATUS(STATUS, "DESC") VALUES('FINISHED', 'FINISHED')
/
INSERT INTO CONTRACT_STATUS(STATUS, "DESC") VALUES('CANCELED', 'CANCELED')
/