INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(1, 'Type 1', 'Description 1')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(2, 'Type 2', 'Description 2')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(3, 'Type 3', 'Description 3')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(4, 'Type 4', 'Description 4')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(5, 'Type 5', 'Description 5')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(6, 'Type 6', 'Description 6')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(7, 'Type 7', 'Description 7')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(8, 'Type 8', 'Description 8')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(9, 'Type 9', 'Description 9')
/
INSERT INTO SERVICE_TYPES(ID, "TYPE", DESCRIPTION) VALUES(10, 'Type 10', 'Description 10')
/