INSERT INTO USER_ROLE(ROLE_TYPE, ROLE_DESC) VALUES ('ADMIN', 'ADMIN')
/
INSERT INTO USER_ROLE(ROLE_TYPE, ROLE_DESC) VALUES ('USER', 'USER')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Admin', 'Admin', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'ADMIN'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'admin'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Admin' AND LAST_NAME = 'Admin'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee1', 'Employee1', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp1', '86ea3363ba65c10f3f1ef299b126de29', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp1'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee1' AND LAST_NAME = 'Employee1'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee2', 'Employee2', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp2', '41ab3465e911f91509d3fae308f41f76', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp2'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee2' AND LAST_NAME = 'Employee2'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee3', 'Employee3', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp3', 'd4de43be683c4a47b9e5b52b2f191cb0', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp3'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee3' AND LAST_NAME = 'Employee3'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee4', 'Employee4', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp4', '4e2750e6d36e8e7ed970ee705ada5c8f', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp4'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee4' AND LAST_NAME = 'Employee4'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee5', 'Employee5', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp5', 'ec06b4fc95d91391e662149794b222d3', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp5'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee5' AND LAST_NAME = 'Employee5'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee6', 'Employee6', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp6', '09d57428ae91c05a90dd39a1bd87df34', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp6'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee6' AND LAST_NAME = 'Employee6'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee7', 'Employee7', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp7', '77780ab2f57504277c55ad44c1b32519', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp7'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee7' AND LAST_NAME = 'Employee7'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee8', 'Employee8', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp8', '261fc5eea5329f26e4a91081d4720c3c', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp8'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee8' AND LAST_NAME = 'Employee8'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee9', 'Employee9', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp9', '67382f06c432c4e691a3886e68ac42e9', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp9'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee9' AND LAST_NAME = 'Employee9'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, "NUMBER") VALUES ('Employee10', 'Employee10', '1970-01-01', 'Polska', '0')
/
INSERT INTO USERS(LOGIN, PASS, PASS_ACTIVE, ENABLED, CREATE_DATE, ROLE_ID) VALUES ('emp10', '2441ff60ab68ee776070a1578d5da59d', 'Y', 'Y', '1970-01-01', (SELECT ID FROM USER_ROLE WHERE ROLE_TYPE = 'USER'))
/
INSERT INTO EMPLOYEES(ACC_ID, PERSON_ID, EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USERS WHERE LOGIN = 'emp10'), (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Employee10' AND LAST_NAME = 'Employee10'), 'testmail@somedomain.com', '00 000 00 00')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer1', 'Customer1', '1970-01-01', 'Polska', 'Province1', 'County1', 'District1', 'Street1', '1', '1', '00-000', 'PostOffice1')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer2', 'Customer2', '1970-01-01', 'Polska', 'Province2', 'County2', 'District2', 'Street2', '2', '2', '00-000', 'PostOffice2')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer3', 'Customer3', '1970-01-01', 'Polska', 'Province3', 'County3', 'District3', 'Street3', '3', '3', '00-000', 'PostOffice3')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer4', 'Customer4', '1970-01-01', 'Polska', 'Province4', 'County4', 'District4', 'Street4', '4', '4', '00-000', 'PostOffice4')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer5', 'Customer5', '1970-01-01', 'Polska', 'Province5', 'County5', 'District5', 'Street5', '5', '5', '00-000', 'PostOffice5')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer6', 'Customer6', '1970-01-01', 'Polska', 'Province6', 'County6', 'District6', 'Street6', '6', '6', '00-000', 'PostOffice6')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer7', 'Customer7', '1970-01-01', 'Polska', 'Province7', 'County7', 'District7', 'Street7', '7', '7', '00-000', 'PostOffice7')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer8', 'Customer8', '1970-01-01', 'Polska', 'Province8', 'County8', 'District8', 'Street8', '8', '8', '00-000', 'PostOffice8')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer9', 'Customer9', '1970-01-01', 'Polska', 'Province9', 'County9', 'District9', 'Street9', '9', '9', '00-000', 'PostOffice9')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer10', 'Customer10', '1970-01-01', 'Polska', 'Province10', 'County10', 'District10', 'Street10', '10', '10', '00-000', 'PostOffice10')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer11', 'Customer11', '1970-01-01', 'Polska', 'Province11', 'County11', 'District11', 'Street11', '11', '11', '00-000', 'PostOffice11')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer12', 'Customer12', '1970-01-01', 'Polska', 'Province12', 'County12', 'District12', 'Street12', '12', '12', '00-000', 'PostOffice12')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer13', 'Customer13', '1970-01-01', 'Polska', 'Province13', 'County13', 'District13', 'Street13', '13', '13', '00-000', 'PostOffice13')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer14', 'Customer14', '1970-01-01', 'Polska', 'Province14', 'County14', 'District14', 'Street14', '14', '14', '00-000', 'PostOffice14')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer15', 'Customer15', '1970-01-01', 'Polska', 'Province15', 'County15', 'District15', 'Street15', '15', '15', '00-000', 'PostOffice15')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer16', 'Customer16', '1970-01-01', 'Polska', 'Province16', 'County16', 'District16', 'Street16', '16', '16', '00-000', 'PostOffice16')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer17', 'Customer17', '1970-01-01', 'Polska', 'Province17', 'County17', 'District17', 'Street17', '17', '17', '00-000', 'PostOffice17')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer18', 'Customer18', '1970-01-01', 'Polska', 'Province18', 'County18', 'District18', 'Street18', '18', '18', '00-000', 'PostOffice18')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer19', 'Customer19', '1970-01-01', 'Polska', 'Province19', 'County19', 'District19', 'Street19', '19', '19', '00-000', 'PostOffice19')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer20', 'Customer20', '1970-01-01', 'Polska', 'Province20', 'County20', 'District20', 'Street20', '20', '20', '00-000', 'PostOffice20')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer21', 'Customer21', '1970-01-01', 'Polska', 'Province21', 'County21', 'District21', 'Street21', '21', '21', '00-000', 'PostOffice21')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer22', 'Customer22', '1970-01-01', 'Polska', 'Province22', 'County22', 'District22', 'Street22', '22', '22', '00-000', 'PostOffice22')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer23', 'Customer23', '1970-01-01', 'Polska', 'Province23', 'County23', 'District23', 'Street23', '23', '23', '00-000', 'PostOffice23')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer24', 'Customer24', '1970-01-01', 'Polska', 'Province24', 'County24', 'District24', 'Street24', '24', '24', '00-000', 'PostOffice24')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer25', 'Customer25', '1970-01-01', 'Polska', 'Province25', 'County25', 'District25', 'Street25', '25', '25', '00-000', 'PostOffice25')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer26', 'Customer26', '1970-01-01', 'Polska', 'Province26', 'County26', 'District26', 'Street26', '26', '26', '00-000', 'PostOffice26')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer27', 'Customer27', '1970-01-01', 'Polska', 'Province27', 'County27', 'District27', 'Street27', '27', '27', '00-000', 'PostOffice27')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer28', 'Customer28', '1970-01-01', 'Polska', 'Province28', 'County28', 'District28', 'Street28', '28', '28', '00-000', 'PostOffice28')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer29', 'Customer29', '1970-01-01', 'Polska', 'Province29', 'County29', 'District29', 'Street29', '29', '29', '00-000', 'PostOffice29')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer30', 'Customer30', '1970-01-01', 'Polska', 'Province30', 'County30', 'District30', 'Street30', '30', '30', '00-000', 'PostOffice30')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer31', 'Customer31', '1970-01-01', 'Polska', 'Province31', 'County31', 'District31', 'Street31', '31', '31', '00-000', 'PostOffice31')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer32', 'Customer32', '1970-01-01', 'Polska', 'Province32', 'County32', 'District32', 'Street32', '32', '32', '00-000', 'PostOffice32')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer33', 'Customer33', '1970-01-01', 'Polska', 'Province33', 'County33', 'District33', 'Street33', '33', '33', '00-000', 'PostOffice33')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer34', 'Customer34', '1970-01-01', 'Polska', 'Province34', 'County34', 'District34', 'Street34', '34', '34', '00-000', 'PostOffice34')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer35', 'Customer35', '1970-01-01', 'Polska', 'Province35', 'County35', 'District35', 'Street35', '35', '35', '00-000', 'PostOffice35')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer36', 'Customer36', '1970-01-01', 'Polska', 'Province36', 'County36', 'District36', 'Street36', '36', '36', '00-000', 'PostOffice36')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer37', 'Customer37', '1970-01-01', 'Polska', 'Province37', 'County37', 'District37', 'Street37', '37', '37', '00-000', 'PostOffice37')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer38', 'Customer38', '1970-01-01', 'Polska', 'Province38', 'County38', 'District38', 'Street38', '38', '38', '00-000', 'PostOffice38')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer39', 'Customer39', '1970-01-01', 'Polska', 'Province39', 'County39', 'District39', 'Street39', '39', '39', '00-000', 'PostOffice39')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer40', 'Customer40', '1970-01-01', 'Polska', 'Province40', 'County40', 'District40', 'Street40', '40', '40', '00-000', 'PostOffice40')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer41', 'Customer41', '1970-01-01', 'Polska', 'Province41', 'County41', 'District41', 'Street41', '41', '41', '00-000', 'PostOffice41')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer42', 'Customer42', '1970-01-01', 'Polska', 'Province42', 'County42', 'District42', 'Street42', '42', '42', '00-000', 'PostOffice42')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer43', 'Customer43', '1970-01-01', 'Polska', 'Province43', 'County43', 'District43', 'Street43', '43', '43', '00-000', 'PostOffice43')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer44', 'Customer44', '1970-01-01', 'Polska', 'Province44', 'County44', 'District44', 'Street44', '44', '44', '00-000', 'PostOffice44')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer45', 'Customer45', '1970-01-01', 'Polska', 'Province45', 'County45', 'District45', 'Street45', '45', '45', '00-000', 'PostOffice45')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer46', 'Customer46', '1970-01-01', 'Polska', 'Province46', 'County46', 'District46', 'Street46', '46', '46', '00-000', 'PostOffice46')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer47', 'Customer47', '1970-01-01', 'Polska', 'Province47', 'County47', 'District47', 'Street47', '47', '47', '00-000', 'PostOffice47')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer48', 'Customer48', '1970-01-01', 'Polska', 'Province48', 'County48', 'District48', 'Street48', '48', '48', '00-000', 'PostOffice48')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer49', 'Customer49', '1970-01-01', 'Polska', 'Province49', 'County49', 'District49', 'Street49', '49', '49', '00-000', 'PostOffice49')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer50', 'Customer50', '1970-01-01', 'Polska', 'Province50', 'County50', 'District50', 'Street50', '50', '50', '00-000', 'PostOffice50')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer51', 'Customer51', '1970-01-01', 'Polska', 'Province51', 'County51', 'District51', 'Street51', '51', '51', '00-000', 'PostOffice51')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer52', 'Customer52', '1970-01-01', 'Polska', 'Province52', 'County52', 'District52', 'Street52', '52', '52', '00-000', 'PostOffice52')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer53', 'Customer53', '1970-01-01', 'Polska', 'Province53', 'County53', 'District53', 'Street53', '53', '53', '00-000', 'PostOffice53')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer54', 'Customer54', '1970-01-01', 'Polska', 'Province54', 'County54', 'District54', 'Street54', '54', '54', '00-000', 'PostOffice54')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer55', 'Customer55', '1970-01-01', 'Polska', 'Province55', 'County55', 'District55', 'Street55', '55', '55', '00-000', 'PostOffice55')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer56', 'Customer56', '1970-01-01', 'Polska', 'Province56', 'County56', 'District56', 'Street56', '56', '56', '00-000', 'PostOffice56')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer57', 'Customer57', '1970-01-01', 'Polska', 'Province57', 'County57', 'District57', 'Street57', '57', '57', '00-000', 'PostOffice57')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer58', 'Customer58', '1970-01-01', 'Polska', 'Province58', 'County58', 'District58', 'Street58', '58', '58', '00-000', 'PostOffice58')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer59', 'Customer59', '1970-01-01', 'Polska', 'Province59', 'County59', 'District59', 'Street59', '59', '59', '00-000', 'PostOffice59')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer60', 'Customer60', '1970-01-01', 'Polska', 'Province60', 'County60', 'District60', 'Street60', '60', '60', '00-000', 'PostOffice60')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer61', 'Customer61', '1970-01-01', 'Polska', 'Province61', 'County61', 'District61', 'Street61', '61', '61', '00-000', 'PostOffice61')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer62', 'Customer62', '1970-01-01', 'Polska', 'Province62', 'County62', 'District62', 'Street62', '62', '62', '00-000', 'PostOffice62')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer63', 'Customer63', '1970-01-01', 'Polska', 'Province63', 'County63', 'District63', 'Street63', '63', '63', '00-000', 'PostOffice63')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer64', 'Customer64', '1970-01-01', 'Polska', 'Province64', 'County64', 'District64', 'Street64', '64', '64', '00-000', 'PostOffice64')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer65', 'Customer65', '1970-01-01', 'Polska', 'Province65', 'County65', 'District65', 'Street65', '65', '65', '00-000', 'PostOffice65')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer66', 'Customer66', '1970-01-01', 'Polska', 'Province66', 'County66', 'District66', 'Street66', '66', '66', '00-000', 'PostOffice66')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer67', 'Customer67', '1970-01-01', 'Polska', 'Province67', 'County67', 'District67', 'Street67', '67', '67', '00-000', 'PostOffice67')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer68', 'Customer68', '1970-01-01', 'Polska', 'Province68', 'County68', 'District68', 'Street68', '68', '68', '00-000', 'PostOffice68')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer69', 'Customer69', '1970-01-01', 'Polska', 'Province69', 'County69', 'District69', 'Street69', '69', '69', '00-000', 'PostOffice69')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer70', 'Customer70', '1970-01-01', 'Polska', 'Province70', 'County70', 'District70', 'Street70', '70', '70', '00-000', 'PostOffice70')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer71', 'Customer71', '1970-01-01', 'Polska', 'Province71', 'County71', 'District71', 'Street71', '71', '71', '00-000', 'PostOffice71')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer72', 'Customer72', '1970-01-01', 'Polska', 'Province72', 'County72', 'District72', 'Street72', '72', '72', '00-000', 'PostOffice72')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer73', 'Customer73', '1970-01-01', 'Polska', 'Province73', 'County73', 'District73', 'Street73', '73', '73', '00-000', 'PostOffice73')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer74', 'Customer74', '1970-01-01', 'Polska', 'Province74', 'County74', 'District74', 'Street74', '74', '74', '00-000', 'PostOffice74')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer75', 'Customer75', '1970-01-01', 'Polska', 'Province75', 'County75', 'District75', 'Street75', '75', '75', '00-000', 'PostOffice75')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer76', 'Customer76', '1970-01-01', 'Polska', 'Province76', 'County76', 'District76', 'Street76', '76', '76', '00-000', 'PostOffice76')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer77', 'Customer77', '1970-01-01', 'Polska', 'Province77', 'County77', 'District77', 'Street77', '77', '77', '00-000', 'PostOffice77')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer78', 'Customer78', '1970-01-01', 'Polska', 'Province78', 'County78', 'District78', 'Street78', '78', '78', '00-000', 'PostOffice78')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer79', 'Customer79', '1970-01-01', 'Polska', 'Province79', 'County79', 'District79', 'Street79', '79', '79', '00-000', 'PostOffice79')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer80', 'Customer80', '1970-01-01', 'Polska', 'Province80', 'County80', 'District80', 'Street80', '80', '80', '00-000', 'PostOffice80')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer81', 'Customer81', '1970-01-01', 'Polska', 'Province81', 'County81', 'District81', 'Street81', '81', '81', '00-000', 'PostOffice81')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer82', 'Customer82', '1970-01-01', 'Polska', 'Province82', 'County82', 'District82', 'Street82', '82', '82', '00-000', 'PostOffice82')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer83', 'Customer83', '1970-01-01', 'Polska', 'Province83', 'County83', 'District83', 'Street83', '83', '83', '00-000', 'PostOffice83')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer84', 'Customer84', '1970-01-01', 'Polska', 'Province84', 'County84', 'District84', 'Street84', '84', '84', '00-000', 'PostOffice84')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer85', 'Customer85', '1970-01-01', 'Polska', 'Province85', 'County85', 'District85', 'Street85', '85', '85', '00-000', 'PostOffice85')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer86', 'Customer86', '1970-01-01', 'Polska', 'Province86', 'County86', 'District86', 'Street86', '86', '86', '00-000', 'PostOffice86')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer87', 'Customer87', '1970-01-01', 'Polska', 'Province87', 'County87', 'District87', 'Street87', '87', '87', '00-000', 'PostOffice87')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer88', 'Customer88', '1970-01-01', 'Polska', 'Province88', 'County88', 'District88', 'Street88', '88', '88', '00-000', 'PostOffice88')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer89', 'Customer89', '1970-01-01', 'Polska', 'Province89', 'County89', 'District89', 'Street89', '89', '89', '00-000', 'PostOffice89')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer90', 'Customer90', '1970-01-01', 'Polska', 'Province90', 'County90', 'District90', 'Street90', '90', '90', '00-000', 'PostOffice90')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer91', 'Customer91', '1970-01-01', 'Polska', 'Province91', 'County91', 'District91', 'Street91', '91', '91', '00-000', 'PostOffice91')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer92', 'Customer92', '1970-01-01', 'Polska', 'Province92', 'County92', 'District92', 'Street92', '92', '92', '00-000', 'PostOffice92')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer93', 'Customer93', '1970-01-01', 'Polska', 'Province93', 'County93', 'District93', 'Street93', '93', '93', '00-000', 'PostOffice93')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer94', 'Customer94', '1970-01-01', 'Polska', 'Province94', 'County94', 'District94', 'Street94', '94', '94', '00-000', 'PostOffice94')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer95', 'Customer95', '1970-01-01', 'Polska', 'Province95', 'County95', 'District95', 'Street95', '95', '95', '00-000', 'PostOffice95')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer96', 'Customer96', '1970-01-01', 'Polska', 'Province96', 'County96', 'District96', 'Street96', '96', '96', '00-000', 'PostOffice96')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer97', 'Customer97', '1970-01-01', 'Polska', 'Province97', 'County97', 'District97', 'Street97', '97', '97', '00-000', 'PostOffice97')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer98', 'Customer98', '1970-01-01', 'Polska', 'Province98', 'County98', 'District98', 'Street98', '98', '98', '00-000', 'PostOffice98')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer99', 'Customer99', '1970-01-01', 'Polska', 'Province99', 'County99', 'District99', 'Street99', '99', '99', '00-000', 'PostOffice99')
/
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, BIRTH_DATE, COUNTRY, PROVINCE, COUNTY, DISTRICT, STREET, "NUMBER", LOCAL_NUMBER, ZIP_CODE, POST_OFFICE) VALUES('Customer100', 'Customer100', '1970-01-01', 'Polska', 'Province100', 'County100', 'District100', 'Street100', '100', '100', '00-000', 'PostOffice100')
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer1' AND LAST_NAME = 'Customer1'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer2' AND LAST_NAME = 'Customer2'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer3' AND LAST_NAME = 'Customer3'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer4' AND LAST_NAME = 'Customer4'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer5' AND LAST_NAME = 'Customer5'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer6' AND LAST_NAME = 'Customer6'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer7' AND LAST_NAME = 'Customer7'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer8' AND LAST_NAME = 'Customer8'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer9' AND LAST_NAME = 'Customer9'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer10' AND LAST_NAME = 'Customer10'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer11' AND LAST_NAME = 'Customer11'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer12' AND LAST_NAME = 'Customer12'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer13' AND LAST_NAME = 'Customer13'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer14' AND LAST_NAME = 'Customer14'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer15' AND LAST_NAME = 'Customer15'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer16' AND LAST_NAME = 'Customer16'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer17' AND LAST_NAME = 'Customer17'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer18' AND LAST_NAME = 'Customer18'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer19' AND LAST_NAME = 'Customer19'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer20' AND LAST_NAME = 'Customer20'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer21' AND LAST_NAME = 'Customer21'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer22' AND LAST_NAME = 'Customer22'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer23' AND LAST_NAME = 'Customer23'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer24' AND LAST_NAME = 'Customer24'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer25' AND LAST_NAME = 'Customer25'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer26' AND LAST_NAME = 'Customer26'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer27' AND LAST_NAME = 'Customer27'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer28' AND LAST_NAME = 'Customer28'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer29' AND LAST_NAME = 'Customer29'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer30' AND LAST_NAME = 'Customer30'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer31' AND LAST_NAME = 'Customer31'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer32' AND LAST_NAME = 'Customer32'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer33' AND LAST_NAME = 'Customer33'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer34' AND LAST_NAME = 'Customer34'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer35' AND LAST_NAME = 'Customer35'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer36' AND LAST_NAME = 'Customer36'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer37' AND LAST_NAME = 'Customer37'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer38' AND LAST_NAME = 'Customer38'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer39' AND LAST_NAME = 'Customer39'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer40' AND LAST_NAME = 'Customer40'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer41' AND LAST_NAME = 'Customer41'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer42' AND LAST_NAME = 'Customer42'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer43' AND LAST_NAME = 'Customer43'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer44' AND LAST_NAME = 'Customer44'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer45' AND LAST_NAME = 'Customer45'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer46' AND LAST_NAME = 'Customer46'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer47' AND LAST_NAME = 'Customer47'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer48' AND LAST_NAME = 'Customer48'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer49' AND LAST_NAME = 'Customer49'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer50' AND LAST_NAME = 'Customer50'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer51' AND LAST_NAME = 'Customer51'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer52' AND LAST_NAME = 'Customer52'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer53' AND LAST_NAME = 'Customer53'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer54' AND LAST_NAME = 'Customer54'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer55' AND LAST_NAME = 'Customer55'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer56' AND LAST_NAME = 'Customer56'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer57' AND LAST_NAME = 'Customer57'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer58' AND LAST_NAME = 'Customer58'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer59' AND LAST_NAME = 'Customer59'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer60' AND LAST_NAME = 'Customer60'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer61' AND LAST_NAME = 'Customer61'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer62' AND LAST_NAME = 'Customer62'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer63' AND LAST_NAME = 'Customer63'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer64' AND LAST_NAME = 'Customer64'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer65' AND LAST_NAME = 'Customer65'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer66' AND LAST_NAME = 'Customer66'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer67' AND LAST_NAME = 'Customer67'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer68' AND LAST_NAME = 'Customer68'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer69' AND LAST_NAME = 'Customer69'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer70' AND LAST_NAME = 'Customer70'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer71' AND LAST_NAME = 'Customer71'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer72' AND LAST_NAME = 'Customer72'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer73' AND LAST_NAME = 'Customer73'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer74' AND LAST_NAME = 'Customer74'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer75' AND LAST_NAME = 'Customer75'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer76' AND LAST_NAME = 'Customer76'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer77' AND LAST_NAME = 'Customer77'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer78' AND LAST_NAME = 'Customer78'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer79' AND LAST_NAME = 'Customer79'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer80' AND LAST_NAME = 'Customer80'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer81' AND LAST_NAME = 'Customer81'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer82' AND LAST_NAME = 'Customer82'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer83' AND LAST_NAME = 'Customer83'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer84' AND LAST_NAME = 'Customer84'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer85' AND LAST_NAME = 'Customer85'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer86' AND LAST_NAME = 'Customer86'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer87' AND LAST_NAME = 'Customer87'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer88' AND LAST_NAME = 'Customer88'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer89' AND LAST_NAME = 'Customer89'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer90' AND LAST_NAME = 'Customer90'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer91' AND LAST_NAME = 'Customer91'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer92' AND LAST_NAME = 'Customer92'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer93' AND LAST_NAME = 'Customer93'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer94' AND LAST_NAME = 'Customer94'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer95' AND LAST_NAME = 'Customer95'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer96' AND LAST_NAME = 'Customer96'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer97' AND LAST_NAME = 'Customer97'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer98' AND LAST_NAME = 'Customer98'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer99' AND LAST_NAME = 'Customer99'))
/
INSERT INTO CUSTOMERS(EMAIL, PHONE_NUMBER, PERSON_ID) VALUES('testmail@somedomain.com', '00 000 00 00', (SELECT ID FROM PERSON WHERE FIRST_NAME = 'Customer100' AND LAST_NAME = 'Customer100'))
/
